Repository PF-GreenFire/GreenFire-BE, pull requests merged in 2024-12, with the labels that each got.

#106 #16 좋아요 갯수 조회
  src/main/java/sisosolsol/greenfire/like/controller/LikeController.java
  src/main/java/sisosolsol/greenfire/like/service/LikeService.java
Labels: feature

#107 #4 챌린지 수정 기능 구현
  src/main/java/sisosolsol/greenfire/challenge/controller/ChallengeController.java
  src/main/java/sisosolsol/greenfire/challenge/model/dao/ChallengeMapper.java
  src/main/java/sisosolsol/greenfire/challenge/service/ChallengeService.java
  src/main/resources/mappers/challenge/ChallengeMapper.xml
Labels: feature

#108 #108 관리자 회원 정보 조회
  src/main/java/sisosolsol/greenfire/common/config/SecurityConfig.java
  src/main/java/sisosolsol/greenfire/common/security/jwt/JwtUtil.java
  src/main/java/sisosolsol/greenfire/user/controller/UserManagementController.java
  src/main/java/sisosolsol/greenfire/user/model/dao/UserMapper.java
  src/main/java/sisosolsol/greenfire/user/model/dto/UserListResponseDTO.java
  src/main/java/sisosolsol/greenfire/user/service/UserManagementService.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: bugfix, feature

#109 gitignore 설정 수정 및 PR 재업로드
  .gitignore
  src/main/java/sisosolsol/greenfire/challenge/model/dto/ChallengeUpdateDTO.java
  src/main/java/sisosolsol/greenfire/challenge/util/ChallengeStatusValidator.java
Labels: merge

#110 #33 관리자 회원 정보 상세 조회
  src/main/java/sisosolsol/greenfire/user/controller/UserManagementController.java
  src/main/java/sisosolsol/greenfire/user/model/dao/UserMapper.java
  src/main/java/sisosolsol/greenfire/user/model/dto/UserDetailResponseDTO.java
  src/main/java/sisosolsol/greenfire/user/service/UserManagementService.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: feature
