Repository PF-GreenFire/GreenFire-BE, pull requests merged in 2024-11, with the labels that each got.

#72 #14 초록불 장소 목록 조회 기능 구현
  src/main/java/sisosolsol/greenfire/config/MybatisConfig.java
  src/main/java/sisosolsol/greenfire/store/controller/StoreController.java
  src/main/java/sisosolsol/greenfire/store/model/dao/StoreMapper.java
  src/main/java/sisosolsol/greenfire/store/model/dto/StoreListDTO.java
  src/main/java/sisosolsol/greenfire/store/model/type/StoreFoodType.java
  src/main/java/sisosolsol/greenfire/store/model/type/StoreStatus.java
  src/main/java/sisosolsol/greenfire/store/service/StoreService.java
  src/main/resources/mappers/store/StoreMapper.xml
Labels: feature

#74 fix: common 위치 수정
  src/main/java/sisosolsol/greenfire/challenge/model/dto/ChallengeCreateDTO.java
  src/main/java/sisosolsol/greenfire/common/ChallengeStatus.java
Labels: style

#73 Iteration1 코드 통합
  src/main/java/sisosolsol/greenfire/category/controller/CategoryController.java
  src/main/java/sisosolsol/greenfire/category/model/dao/CategoryMapper.java
  src/main/java/sisosolsol/greenfire/category/model/dto/CategoryCreateDTO.java
  src/main/java/sisosolsol/greenfire/category/model/dto/CategoryUpdateDTO.java
  src/main/java/sisosolsol/greenfire/category/model/type/CategoryType.java
  src/main/java/sisosolsol/greenfire/category/service/CategoryService.java
  src/main/java/sisosolsol/greenfire/challenge/controller/ChallengeController.java
  src/main/java/sisosolsol/greenfire/challenge/model/dao/ChallengeMapper.java
  src/main/java/sisosolsol/greenfire/challenge/model/dto/ChallengeCreateDTO.java
  src/main/java/sisosolsol/greenfire/challenge/service/ChallengeService.java
  src/main/java/sisosolsol/greenfire/common/ChallengeStatus.java
  src/main/java/sisosolsol/greenfire/config/MybatisConfig.java
  src/main/resources/mappers/category/CategoryMapper.xml
  src/main/resources/mappers/challenge/ChallengeMapper.xml
Labels: merge

#85 #55 포스트 수정 기능 구현
  src/main/java/sisosolsol/greenfire/image/model/dao/ImageMapper.java
  src/main/java/sisosolsol/greenfire/image/service/ImageService.java
  src/main/java/sisosolsol/greenfire/post/controller/PostController.java
  src/main/java/sisosolsol/greenfire/post/model/dao/PostMapper.java
  src/main/java/sisosolsol/greenfire/post/model/dto/PostUpdateDTO.java
  src/main/java/sisosolsol/greenfire/post/service/PostService.java
  src/main/resources/mappers/image/ImageMapper.xml
  src/main/resources/mappers/post/PostMapper.xml
Labels: feature

#84 #1 챌린지 조회 기능
  src/main/java/sisosolsol/greenfire/challenge/controller/ChallengeController.java
  src/main/java/sisosolsol/greenfire/challenge/model/dao/ChallengeMapper.java
  src/main/java/sisosolsol/greenfire/challenge/model/dto/ChallengeCreateDTO.java
  src/main/java/sisosolsol/greenfire/challenge/model/dto/ChallengeDTO.java
  src/main/java/sisosolsol/greenfire/challenge/model/dto/ChallengeSearchCondition.java
  src/main/java/sisosolsol/greenfire/challenge/model/dto/ChallengeSearchDTO.java
  src/main/java/sisosolsol/greenfire/challenge/service/ChallengeService.java
  src/main/resources/mappers/challenge/ChallengeMapper.xml
Labels: feature

#86 #17 장소 신청 등록
  src/main/java/sisosolsol/greenfire/image/model/dao/ImageMapper.java
  src/main/java/sisosolsol/greenfire/image/service/ImageService.java
  src/main/java/sisosolsol/greenfire/location/model/dao/LocationMapper.java
  src/main/java/sisosolsol/greenfire/location/model/dto/LocationDTO.java
  src/main/java/sisosolsol/greenfire/location/service/LocationService.java
  src/main/java/sisosolsol/greenfire/store/controller/StoreController.java
  src/main/java/sisosolsol/greenfire/store/model/dao/StoreMapper.java
  src/main/java/sisosolsol/greenfire/store/model/dto/StoreCreateDTO.java
  src/main/java/sisosolsol/greenfire/store/service/StoreService.java
  src/main/resources/mappers/image/ImageMapper.xml
  src/main/resources/mappers/location/LocationMapper.xml
  src/main/resources/mappers/store/StoreMapper.xml
Labels: feature

#98 #97 회원 프로필 정보 조회
  src/main/java/sisosolsol/greenfire/common/config/SecurityConfig.java
  src/main/java/sisosolsol/greenfire/common/enums/user/Gender.java
  src/main/java/sisosolsol/greenfire/common/enums/user/UserStatus.java
  src/main/java/sisosolsol/greenfire/common/exception/type/ExceptionCode.java
  src/main/java/sisosolsol/greenfire/user/controller/UserController.java
  src/main/java/sisosolsol/greenfire/user/model/dao/UserMapper.java
  src/main/java/sisosolsol/greenfire/user/model/dto/UserDTO.java
  src/main/java/sisosolsol/greenfire/user/service/UserService.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: feature

#100 #26 관리자 장소 정보 수정
  src/main/java/sisosolsol/greenfire/image/model/dao/ImageMapper.java
  src/main/java/sisosolsol/greenfire/image/service/ImageService.java
  src/main/java/sisosolsol/greenfire/store/controller/StoreController.java
  src/main/java/sisosolsol/greenfire/store/model/dao/StoreMapper.java
  src/main/java/sisosolsol/greenfire/store/service/StoreService.java
  src/main/resources/mappers/image/ImageMapper.xml
  src/main/resources/mappers/store/StoreMapper.xml
Labels: refactor, feature

#103 #93 챌린지 상세 조회 기능
  src/main/java/sisosolsol/greenfire/challenge/controller/ChallengeController.java
  src/main/java/sisosolsol/greenfire/challenge/service/ChallengeService.java
  src/main/resources/mappers/store/StoreMapper.xml
Labels: feature

#102 #102 회원 프로필 정보 수정 기능 구현
  src/main/java/sisosolsol/greenfire/user/controller/UserController.java
  src/main/java/sisosolsol/greenfire/user/model/dao/UserMapper.java
  src/main/java/sisosolsol/greenfire/user/model/dto/UserUpdateDTO.java
  src/main/java/sisosolsol/greenfire/user/service/UserService.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: feature

#105 #15 좋아요 적용 및 취소
  build.gradle
  src/main/java/sisosolsol/greenfire/common/config/RedisConfig.java
  src/main/java/sisosolsol/greenfire/common/enums/like/LikeType.java
  src/main/java/sisosolsol/greenfire/like/controller/LikeController.java
  src/main/java/sisosolsol/greenfire/like/model/dao/LikeMapper.java
  src/main/java/sisosolsol/greenfire/like/model/dto/LikeDTO.java
  src/main/java/sisosolsol/greenfire/like/service/LikeService.java
  src/main/resources/mappers/like/LikeMapper.xml
Labels: doc, feature
